### ISSUE TITLE
County-specific logic: Oakland children

### ISSUE THREAD

**Issue by normon66** [mplp/docassemble-MLHPPOAndProposedOrder#121]
When filing in Oakland County, information about children should be asked and included in the Statement of Facts.

1. At a glance, information about children [in common] should include:

 - Name / DOB
 - Where currently lives
 - Paternity details
 - Parentage
 - Previous custody or parenting time orders
 - Keep or change existing orders

2. Name and DOB/age of other children living in the home of either party

One example of Statement of Facts output:
![image](https://github.com/user-attachments/assets/657627f1-0358-4791-bc38-a02455190a76)

See full details in [this Google doc](https://docs.google.com/document/d/1u4ZXaOIqWMMn5N4iTVrW49AGxyDDb_Fe/edit).

**Comment by normon66** [comment]
In the A2J tool, I also included logic to skip the children intro page if we already knew they do have children, or to skip the entire section if we know that they do not have children. This was based on the previous 'relationship with respondent' page (third image below).

![image](https://github.com/user-attachments/assets/f6bce676-98ce-4812-a495-38f348141eef)

![image](https://github.com/user-attachments/assets/1c26a683-fb02-4e39-b1ad-3171546572dc)
 
![image](https://github.com/user-attachments/assets/46a5b146-e495-4f8f-84ad-35fd4045b4c2)

**Comment by ekressmiller** [comment]
Just a note for my future peace of mind because I keep second guessing myself. It looks from LHI testing (Brett if you see this feel free to confirm) like we ask in detail about about kids in Oakland only for domestic petitions. 

If it's nondomestic or sexual assault (Oakland only), we ask about kids in common only in order to force them to use the domestic track if appropriate. We don't ask at all about other kids.

**Comment by normon66** [comment]
Just seeing this! You are correct. Details on minor children in common and "other children" are only gathered for domestic Oakland PPOs. The nondomestic/sexual assault tracks only ask the initial question about children in common to check if the user should be using a domestic petition, as you also pointed out.
