### ISSUE TITLE
County-specific logic: Oakland and Wayne relationship descriptions

### ISSUE THREAD

**Issue by normon66** [mplp/docassemble-MLHPPOAndProposedOrder#123]
For Oakland and Wayne counties, we sometimes include an open text field to collect the user's description of their relationship with the respondent (in addition to the normal checkboxes). This is then included on the Statement of Facts.

In the below screenshot, a `Type of PPO MC` of 1 is domestic, 2 is non-domestic stalking, and 3 is non-domestic sexual assault.
![image](https://github.com/user-attachments/assets/75be37bd-832b-44f8-89e7-560ed842a260)

Slightly different text is included in these pages, depending on whether it's domestic or non-domestic.

Page "2.1 Relationship Details Domestic":
![image](https://github.com/user-attachments/assets/83dbde97-bae9-47ca-923c-3250286c95fd)

Page "2.2 Relationship Details Nondomestic":
![image](https://github.com/user-attachments/assets/2794683e-658d-45f2-990a-358eaa6f0d22)

Sample form output on domestic PPO:
![image](https://github.com/user-attachments/assets/9d638cad-a606-485f-8a89-dec4c2c14750)

**Comment by RamiLorca** [comment]
@normon66 In the A2J version, this screen didn't come up for me when I selected a domestic PPO and either Oakland or Wayne counties. Has the logic been changed? Or is there maybe a specific combination of checkboxes that triggers this question?

**Comment by normon66** [comment]
@RamiLorca - I'm glad you caught this! There is indeed one additional layer of conditional logic here.

If a domestic PPO for Oakland or Wayne and the relationship is one of the options checked in the image below, the open text relationship page is skipped.
![image](https://github.com/user-attachments/assets/b6d3f274-8555-4a5b-929a-21a321865fbc)
![image](https://github.com/user-attachments/assets/a49c3728-e848-4805-bef7-e34ff2a58c48)

Instead, the HotDocs computation automatically inserts one of these short phrases:
![image](https://github.com/user-attachments/assets/14ee33b7-de4a-45bc-a66b-67e9ef16ffd0)

**Comment by ekressmiller** [comment]
@normon66 Looks like our logic is currently incomplete for adding "The parties currently reside together" or "The parties do not currently reside together" to the statement of facts. Am I correct that:

- this should be set by the "Do you and [respondent] live together?" question. If yes, print that they currently reside, if no print that they do not.
- applies to domestic petitions only
- applies to all counties

Thanks, apologies if you have already shared this somewhere!

**Comment by normon66** [comment]
@ekressmiller - you are correct. The "Do you... live together?" question should be asked for all counties when a domestic PPO (and _only_ when domestic), and one of these two statements below should always appear on the statement of facts.

![image](https://github.com/user-attachments/assets/d130afc5-5c44-4567-aaf4-51566a7c0e51)

**Comment by ekressmiller** [comment]
@normon66 thank you! Adding this fix to #192
