### ISSUE TITLE
County-specific logic: Email to Court (ETC) options

### ISSUE THREAD

**Issue by normon66** [mplp/docassemble-MLHPPOAndProposedOrder#127]
Once ETC has been developed, there are counties that only allow for ETC and some that provide the option. Counties, email addresses, and page flows are shown below. 

**The following counties should _only_ allow ETC:**
- Oakland (ppo@oakgov.com)
- Wayne (ppo@3rdcc.org)

Flow:
1. Page 1: 

> You will email your forms directly to Oakland County Circuit Court directly from this tool.
> Review the instructions that you will get with your forms for more information.

2. Page 2:

> What is your email address?
> Enter an email address that you check often and do not share with anyone else.
> [email text field]

3. Moves on to standard "You have finished answer questions..." etc outro pages.

**The following counties should provide for ETC as an _option_:**
- Cass (ccfileroom@cassco.org)
- Gogebic (efile@gogebiccountymi.gov)
- Ionia (clerk@ioniacounty.org)
- Iosco (countyclerk@ioscocounty.org)
- Marquette (countyclerk@mqtco.org)
- Montcalm (clerk@montcalm.us)

1. Page 1:

> You are able to email your forms to the Cass County Circuit Court directly from this tool so that you do not need to download and email or electronically file them yourself. 
> Would you like to have this tool email your forms for you?
> [ Yes / No ]

2. Page 2a (if Yes):

> What is your email address?
> Enter an email address that you check often and do not share with anyone else.
> [email text field]

2. Page 2b (if No): Continues to "Completing this process does not file your forms..." etc outro pages. 

3. Moves on to standard "You have finished answer questions..." etc outro pages.

**Comment by ekressmiller** [comment]
logic is basically there now, but still want to review this more closely to see if want to snag any more of this language.

**Comment by ekressmiller** [comment]
still need to set up email address in config to actually go to the courts.

**Comment by ekressmiller** [comment]
still need to set up email address in config to actually go to the courts of course, but we'll test that later.
