### ISSUE TITLE
Petitioner name is very small in caption on Petition

### ISSUE THREAD

**Issue by MPLP-Docassemble** [mplp/docassemble-MLHPPOAndProposedOrder#147]
&nbsp; | &nbsp;
-------|------------------------------------
Question ID | `email to court success screen`
Variable sought | `ETC_success`
Package version | `playground`
Form | `docassemble.playground4PPO:ppo_and_proposed_order.yml`

**Details:** 

Petitioner's name appears extremely small on the Petition in the caption at the top even though there is more vertical space available.

**Comment by ekressmiller** [comment]
<img width="616" alt="image" src="https://github.com/user-attachments/assets/fbda166b-983a-4f1a-a38c-41614e2e75c7">

**Comment by ekressmiller** [comment]
this is the nondomestic sexual assault petition CC 395
