### ISSUE TITLE
ID ppo_harm_protectees name: 
User feedback: language
(`ppo_harm_protectees[2].name.first`)

### ISSUE THREAD

**Issue by MPLP-Docassemble** [mplp/docassemble-MLHPPOAndProposedOrder#15]
&nbsp; | &nbsp;
-------|------------------------------------
Question ID | `ppo_harm_protectees name`
Details | I think the "the second other person" etc. language could be confusing. Can you change it to just "the other person"?
Variable being sought | `ppo_harm_protectees[2].name.first`
Package version | `0.0.6`
Filename | `docassemble.MLHPPOAndProposedOrder:data/questions/ppo_and_proposed_order.yml`

**Comment by ekressmiller** [comment]
Never mind, I see that it's this way in a similar question in the LHI version, so let's leave it alone for now.
