### ISSUE TITLE
Tester feedback: language
(`domestic_ppo_children_intro`)

### ISSUE THREAD

**Issue by MPLP-Docassemble** [mplp/docassemble-MLHPPOAndProposedOrder#163]
&nbsp; | &nbsp;
-------|------------------------------------
Question ID | `domestic ppo children intro`
Variable sought | `domestic_ppo_children_intro`
Package version | `playground`
Form | `docassemble.playground4PPO:ppo_and_proposed_order.yml`

**Details:** 

It seems like we should ask about children more sensitively. Looks like LHI does it this way too, so this would be an enhancement.

**Comment by ekressmiller** [comment]
#166 makes a minor change so that it makes more sense if there are no children in common (and doesn't unnecessarily suggest incest)
