### ISSUE TITLE
Tester feedback: language
(`petitioner_has_other_children`)

### ISSUE THREAD

**Issue by MPLP-Docassemble** [mplp/docassemble-MLHPPOAndProposedOrder#164]
&nbsp; | &nbsp;
-------|------------------------------------
Question ID | `petitioner's other children`
Variable sought | `petitioner_has_other_children`
Package version | `playground`
Form | `docassemble.playground4PPO:ppo_and_proposed_order.yml`

**Details:** 

It went right to this after telling me it would ask about children. Seems like before asking if I have any "other children" it should first ask if there are any children. (But also see previous note about this question when respondent is a parent.)

**Comment by ekressmiller** [comment]
#166 closes this -just removed the word "other" since it seems confusing whether or not the petitioner and respondent have kids in common
