### ISSUE TITLE
Tester feedback: language
(`respondent_has_other_children`)

### ISSUE THREAD

**Issue by MPLP-Docassemble** [mplp/docassemble-MLHPPOAndProposedOrder#165]
&nbsp; | &nbsp;
-------|------------------------------------
Question ID | `respondent's other children`
Variable sought | `respondent_has_other_children`
Package version | `playground`
Form | `docassemble.playground4PPO:ppo_and_proposed_order.yml`

**Details:** 

again, this question feels odd when I said respondent was my parent

**Comment by ekressmiller** [comment]
removed word "other" since it seems confusing either way
