### ISSUE TITLE
Tester feedback: something
(`petitioner_respondent_relationship`)

### ISSUE THREAD

**Issue by MPLP-Docassemble** [mplp/docassemble-MLHPPOAndProposedOrder#167]
&nbsp; | &nbsp;
-------|------------------------------------
Question ID | `relationship to respondent`
Variable sought | `petitioner_respondent_relationship`
Package version | `playground`
Form | `docassemble.playground4PPO:ppo_and_proposed_order.yml`

**Details:** 

Is the change in language from LHI intentional?

**Comment by ekressmiller** [comment]
![image](https://github.com/user-attachments/assets/27fbf3a5-55a9-402c-837c-14e32352ec46)

vs.

<img width="261" alt="image" src="https://github.com/user-attachments/assets/e5751070-b162-4c50-8fdb-b3ad67d59853">


Apologies if this is something you covered with Brett, just noticed and wanted to check.
