### ISSUE TITLE
ID ppo_harm_protectees there_is_another: 
User feedback: language
(`ppo_harm_protectees.there_is_another`)

### ISSUE THREAD

**Issue by MPLP-Docassemble** [mplp/docassemble-MLHPPOAndProposedOrder#17]
&nbsp; | &nbsp;
-------|------------------------------------
Question ID | `ppo_harm_protectees there_is_another`
Details | Spacing is uneven in the bulleted list of people.
Variable being sought | `ppo_harm_protectees.there_is_another`
Package version | `0.0.6`
Filename | `docassemble.MLHPPOAndProposedOrder:data/questions/ppo_and_proposed_order.yml`

**Comment by ekressmiller** [comment]
![image](https://github.com/mplp/docassemble-MLHPPOAndProposedOrder/assets/110936328/a479fba2-a4d5-4242-a203-301645033da5)
