### ISSUE TITLE
Tester feedback: bug
(`email_status`)

### ISSUE THREAD

**Issue by MPLP-Docassemble** [mplp/docassemble-MLHPPOAndProposedOrder#173]
&nbsp; | &nbsp;
-------|------------------------------------
Question ID | `email confirmation page`
Variable sought | `email_status`
Package version | `playground`
Form | `docassemble.playground4PPO:ppo_and_proposed_order.yml`

**Details:** 

Age/birthday is blank on Identifying Information attachment.

**Comment by ekressmiller** [comment]
![image](https://github.com/user-attachments/assets/db1b9638-8484-4115-bdfc-1c95697cc0ea)
