### ISSUE TITLE
Tester feedback: something
(`ETC_success`)

### ISSUE THREAD

**Issue by MPLP-Docassemble** [mplp/docassemble-MLHPPOAndProposedOrder#174]
&nbsp; | &nbsp;
-------|------------------------------------
Question ID | `email to court success screen`
Variable sought | `ETC_success`
Package version | `playground`
Form | `docassemble.playground4PPO:ppo_and_proposed_order.yml`

**Details:** 

In LHI, the "Identifying Information" attachment comes out as part of the Petition rather than as a separate download. In the Docassemble version, it comes out separately.

Unless this is an intentional change or overly complicated, I think we should do the same here.

**Comment by ekressmiller** [comment]
[LHI version--Email to Court Cover Sheet with Petition.pdf](https://github.com/user-attachments/files/17497339/LHI.version--Email.to.Court.Cover.Sheet.with.Petition.pdf)
