### ISSUE TITLE
Tester feedback: something
(`next_friend_signature_notice`)

### ISSUE THREAD

**Issue by MPLP-Docassemble** [mplp/docassemble-MLHPPOAndProposedOrder#175]
&nbsp; | &nbsp;
-------|------------------------------------
Question ID | `next friend signature notice`
Variable sought | `next_friend_signature_notice`
Package version | `playground`
Form | `docassemble.playground4PPO:ppo_and_proposed_order.yml`

**Details:** 

Question for Brett/Amy. Is there a reason we have this special warning screen when next friends decline to e-sign? Is it necessary? If so, should we include it for the petitioner when there's no next friend as well? It seems odd to include it for next friends only. 

If we keep it, we should re-write it because they still have a chance to e-sign later.

We could also rewrite it as help text instead of a separate screen.

**Comment by ekressmiller** [comment]
Question sent by email 10/24
