### ISSUE TITLE
Asks for respondent address even though I said we live together.

### ISSUE THREAD

**Issue by MPLP-Docassemble** [mplp/docassemble-MLHPPOAndProposedOrder#194]
&nbsp; | &nbsp;
-------|------------------------------------
Question ID | `respondent contact info`
Variable sought | `other_parties[0].address.address`
Package version | `playground`
Form | `docassemble.playground4PPObugSquashing:ppo_and_proposed_order.yml`

**Details:** 

I answered yes to petitioner_and_respondent_living_together but it's still asking for respondent address. Is that correct? 

Oakland, both adults, I said I don't live in MI and respondent does (which maybe I shouldn't be able to do . . .).  Same test as #193.

**Comment by ekressmiller** [comment]
Note, it does correctly give my address on the form output though.
![image](https://github.com/user-attachments/assets/ba2c85f4-4f8c-4b7f-b51e-e08195a12cb3)
