### ISSUE TITLE
Tester feedback: bug
(`children[0].desired_parenting_time_changes`)

### ISSUE THREAD

**Issue by MPLP-Docassemble** [mplp/docassemble-MLHPPOAndProposedOrder#196]
&nbsp; | &nbsp;
-------|------------------------------------
Question ID | `desired parenting time change for individual child`
Variable sought | `children[0].desired_parenting_time_changes`
Package version | `playground`
Form | `docassemble.playground4PPObugSquashing:ppo_and_proposed_order.yml`

**Details:** 

I said there is no parenting time order, but it still asks these questions about wanting to continue parenting time arrangements

**Comment by ekressmiller** [comment]
same in LHI.
