### ISSUE TITLE
Tester feedback: bug
(`ETC_review_docs_screen`)

### ISSUE THREAD

**Issue by MPLP-Docassemble** [mplp/docassemble-MLHPPOAndProposedOrder#197]
&nbsp; | &nbsp;
-------|------------------------------------
Question ID | `ETC review and download docs DownloadScreen`
Variable sought | `ETC_review_docs_screen`
Package version | `playground`
Form | `docassemble.playground4PPObugSquashing:ppo_and_proposed_order.yml`

**Details:** 

I said Respondent has other children (not with petitioner) with names unknown. On the statement of facts it says Respondent has no other child.

**Comment by ekressmiller** [comment]
See output and info on testing path here: [Petition for Personal Protection Order Domestic Relationship - CC 375 (7).pdf](https://github.com/user-attachments/files/17588879/Petition.for.Personal.Protection.Order.Domestic.Relationship.-.CC.375.7.pdf)

**Comment by ekressmiller** [comment]
should look like this as in LHI:
