### ISSUE TITLE
Tester feedback: bug
(`ETC_review_docs_screen`)

### ISSUE THREAD

**Issue by MPLP-Docassemble** [mplp/docassemble-MLHPPOAndProposedOrder#198]
&nbsp; | &nbsp;
-------|------------------------------------
Question ID | `ETC review and download docs DownloadScreen`
Variable sought | `ETC_review_docs_screen`
Package version | `playground`
Form | `docassemble.playground4PPObugSquashing:ppo_and_proposed_order.yml`

**Details:** 

I entered that petitioner and respondent have a child, but it's not showing up on the statement of facts.
I said: Little Timmy, DOB 10/10/2020, no custody/pt order, leave custody/pt the same.  Currently lives with respondent (though note I said we live together as well). Yes married when born.

**Comment by ekressmiller** [comment]
[Petition for Personal Protection Order Domestic Relationship - CC 375 (7).pdf](https://github.com/user-attachments/files/17588926/Petition.for.Personal.Protection.Order.Domestic.Relationship.-.CC.375.7.pdf)

**Comment by ekressmiller** [comment]
should look like this per LHI: 
![image](https://github.com/user-attachments/assets/75d1ebc5-d951-4c10-b586-eed9de0b716e)
