### ISSUE TITLE
Proof of Service issues

### ISSUE THREAD

**Issue by ekressmiller** [mplp/docassemble-MLHPPOAndProposedOrder#203]
Not entirely clear on scope of issue yet. But it looks like we currently have the _Petition_ proof of service in the same download with the _Order_ (edited to add, this turned out to be true of the domestic adult order only).  I think the Petition proof of service should generate separately. And an _Order_ proof of service should generate with the order.

It also appears we're not generating the petition proof of service when we should be.

**Comment by ekressmiller** [comment]
Here is an Oakland example from LHI. Domestic. NOT ex parte. No minors parties.
![image](https://github.com/user-attachments/assets/235d2734-2e53-4dbb-ab8f-8854c8688a98)
Note separate Proof of Service entry in the download list, which gives you this: [Proof of Service.pdf](https://github.com/user-attachments/files/17651474/Proof.of.Service.8.pdf). Note language that says you must serve the "Petition".
The Order from that download list gives you: [Personal Protection Order (Domestic) - CC 376.pdf](https://github.com/user-attachments/files/17651493/Personal.Protection.Order.Domestic.-.CC.376.7.pdf). Note the language about serving the "order."

**Comment by ekressmiller** [comment]
Whereas in Docassemble, Oakland, domestic, NOT ex parte, no minor parties, the proposed order has an attached POS that mentions serving the "petition":
[Proposed Order (15).pdf](https://github.com/user-attachments/files/17651508/Proposed.Order.15.pdf)

And there is no freestanding proof of service download:
![image](https://github.com/user-attachments/assets/948aa0c6-a800-4ffc-939f-a971669d4689)

**Comment by ekressmiller** [comment]
Also, remember wayne wants no Proof of Service at all.

**Comment by RamiLorca** [comment]
![Screenshot 2024-11-13 at 2 18 27 PM (2)](https://github.com/user-attachments/assets/1e14a36b-09bd-4bd1-9719-d91907832d2f)
