### ISSUE TITLE
Don't allow editing of is_incapacitated_adult

### ISSUE THREAD

**Issue by ekressmiller** [mplp/docassemble-MLHPPOAndProposedOrder#224]
Since I think we decided not to allow them to change answer to is_incapacitated_adult, that should not be editable. However, if true, I think we should still display on the review screen a note saying something like "The person who needs protection _[or users[0].name if feasible]_ is an incapacitated adult." Probably don't display any message if it's not for an incapacitate adult.

**Comment by ekressmiller** [comment]
@RamiLorca or did you decide this one was OK to allow to edit?

**Comment by RamiLorca** [comment]
> @RamiLorca or did you decide this one was OK to allow to edit?

That's correct. I'll take care of this fix.
