### ISSUE TITLE
ID intro navigation: 
User feedback: language
(`MLH_intro_navigation`)

### ISSUE THREAD

**Issue by MPLP-Docassemble** [mplp/docassemble-MLHPPOAndProposedOrder#45]
&nbsp; | &nbsp;
-------|------------------------------------
Question ID | `intro navigation`
Details | This page still contains A2J-specific language.
Variable being sought | `MLH_intro_navigation`
Package version | `0.0.6`
Filename | `docassemble.MLHPPOAndProposedOrder:data/questions/ppo_and_proposed_order.yml`

**Comment by RamiLorca** [comment]
<img width="836" alt="MLH Nav Screen" src="https://github.com/mplp/docassemble-MLHPPOAndProposedOrder/assets/110207826/04ab64e7-b008-493e-a1c7-2099e220f186">

Are you referring to the "Review/Edit" part?

**Comment by normon66** [comment]
That all looks correct now. It must have been an interim version or just a mistake. Sorry about that (if that was me)!
