### ISSUE TITLE
ID abuse history intro 3: 
User feedback: something
(`abuse_history_intro_3`)

### ISSUE THREAD

**Issue by MPLP-Docassemble** [mplp/docassemble-MLHPPOAndProposedOrder#52]
&nbsp; | &nbsp;
-------|------------------------------------
Question ID | `abuse history intro 3`
Details | Consider putting the question text into the subquestion and writing a shorter question, such as "Attaching Evidence"
Variable being sought | `abuse_history_intro_3`
Package version | `0.0.6`
Filename | `docassemble.MLHPPOAndProposedOrder:data/questions/ppo_and_proposed_order.yml`

**Comment by normon66** [comment]
This came across my mind following our recent team meeting, where we discussed keeping question text to 1 line if possible, sometimes 2. There are actually quite a few screens where the question text goes to 3 lines, even on a full-sized monitor, but some of them actually work well in my opinion. Your discretion on how to handle those longer-questioned pages.
