### ISSUE TITLE
Respondent name included in address/phone field

### ISSUE THREAD

**Issue by normon66** [mplp/docassemble-MLHPPOAndProposedOrder#63]
On CC 380 (and possibly other forms?), the respondent's name is unnecessarily included in the contact info field. 

![image](https://github.com/mplp/docassemble-MLHPPOAndProposedOrder/assets/32527754/1cc60927-d57a-47aa-9396-8d636b72d0c5)

**Comment by normon66** [comment]
I see in Rami's original email from April 25 that this may already be resolved in another [non-published] branch.

> When generating a non-domestic PPO form (CC 380), the field with the other party's address and telephone number will (redundantly) include the person's name. Also, the judicial circuit font won't be bolded. These were two last-minute issues I spotted and corrected in a new branch. However, for the purpose of testing the work on the main branch, please disregard them.

**Comment by RamiLorca** [comment]
Fixed
