### ISSUE TITLE
ID next friend: 
User feedback: language
(`minor_has_next_friend`)

### ISSUE THREAD

**Issue by MPLP-Docassemble** [mplp/docassemble-MLHPPOAndProposedOrder#65]
&nbsp; | &nbsp;
-------|------------------------------------
Question ID | `next friend`
Details | This page is missing the Learn More text as seen in A2J Author.
Variable being sought | `minor_has_next_friend`
Package version | `playground`
Filename | `docassemble.playground5PPO:ppo_and_proposed_order.yml`

**Comment by normon66** [comment]
Prompt: What does a next friend need to do?
Answer:
```
A next friend will need to:

1. File your forms for you, which can sometimes be done online, but must sometimes be done in person;
2. Arrange to have court papers delivered to the other party;
3. Attend the hearing, if you have one, and speak on your behalf.

Make sure that your next friend can do **all** of these things.
```

![image](https://github.com/mplp/docassemble-MLHPPOAndProposedOrder/assets/32527754/0c8e2f94-3fde-4c12-9554-886275a86dcc)

**Comment by normon66** [comment]
Just now seeing on your email from April 25 that these features were still in development at that time. Sorry if this is hasty.
