### ISSUE TITLE
ID minor_kickout: 
User feedback: something
(`minor_kickout`)

### ISSUE THREAD

**Issue by MPLP-Docassemble** [mplp/docassemble-MLHPPOAndProposedOrder#66]
&nbsp; | &nbsp;
-------|------------------------------------
Question ID | `minor_kickout`
Details | Numerous changes needed on this page:

1. Title of Petition... should be in italics
2. Go Back should be Undo (MLH_back_button_label)
3. There is no Exit button. Revise text or add button.
4. Minors and Personal Protection Orders should be a hyperlink to https://michiganlegalhelp.org/self-help-tools/personal-safety/minors-and-personal-protection-orders
Variable being sought | `minor_kickout`
Package version | `playground`
Filename | `docassemble.playground5PPO:ppo_and_proposed_order.yml`

**Comment by normon66** [comment]
Just now seeing on your email from April 25 that these features were still in development at that time. Sorry if this is hasty.
