### ISSUE TITLE
ID incidents outro: 
User feedback: bug
(`incidents_outro`)

### ISSUE THREAD

**Issue by MPLP-Docassemble** [mplp/docassemble-MLHPPOAndProposedOrder#86]
&nbsp; | &nbsp;
-------|------------------------------------
Question ID | `incidents outro`
Details | I said the police were NOT called, but this screen still showed up. In the LHI version, this screen only shows up if you say the police were called.
Variable being sought | `incidents_outro`
Package version | `0.0.6`
Filename | `docassemble.MLHPPOAndProposedOrder:data/questions/ppo_and_proposed_order.yml`

**Comment by ekressmiller** [comment]
The above related to the first incident I entered.

I added a second incident, and said the police WERE called, but this screen did not show up.
